import { registerAreaSeries } from "../entries/series/area.js";
import { registerBoxplotSeries } from "../entries/series/boxplot.js";
import { registerBubbleSeries } from "../entries/series/bubble.js";
import { registerBulletSeries } from "../entries/series/bullet.js";
import { registerCalendarSeries } from "../entries/series/calendar.js";
import { registerCandlestickSeries } from "../entries/series/candlestick.js";
import { registerColumnSeries } from "../entries/series/column.js";
import { registerColumnRangeSeries } from "../entries/series/columnrange.js";
import { registerDumbbellSeries } from "../entries/series/dumbbell.js";
import { registerErrorBarSeries } from "../entries/series/errorbar.js";
import { registerFunnelSeries } from "../entries/series/funnel.js";
import { registerGanttSeries } from "../entries/series/gantt.js";
import { registerGaugeSeries } from "../entries/series/gauge.js";
import { registerHeatmapSeries } from "../entries/series/heatmap.js";
import { registerHistogramSeries } from "../entries/series/histogram.js";
import { registerLineSeries } from "../entries/series/line.js";
import { registerLollipopSeries } from "../entries/series/lollipop.js";
import { registerMarimekkoSeries } from "../entries/series/marimekko.js";
import { registerPieSeries } from "../entries/series/pie.js";
import { registerRadarSeries } from "../entries/series/radar.js";
import { registerRadialBarSeries } from "../entries/series/radialbar.js";
import { registerRangeSeries } from "../entries/series/range.js";
import { registerSankeySeries } from "../entries/series/sankey.js";
import { registerScatterSeries } from "../entries/series/scatter.js";
import { registerSlopeSeries } from "../entries/series/slope.js";
import { registerSparklineSeries } from "../entries/series/sparkline.js";
import { registerSunburstSeries } from "../entries/series/sunburst.js";
import { registerTimelineSeries } from "../entries/series/timeline.js";
import { registerTreegraphSeries } from "../entries/series/treegraph.js";
import { registerWaterfallSeries } from "../entries/series/waterfall.js";

/** Re-register every built-in family, useful after deliberately replacing one. */
export function registerAllSeries(): void {
  registerAreaSeries();
  registerBoxplotSeries();
  registerBubbleSeries();
  registerBulletSeries();
  registerCalendarSeries();
  registerCandlestickSeries();
  registerColumnSeries();
  registerColumnRangeSeries();
  registerDumbbellSeries();
  registerErrorBarSeries();
  registerFunnelSeries();
  registerGanttSeries();
  registerGaugeSeries();
  registerHeatmapSeries();
  registerHistogramSeries();
  registerLineSeries();
  registerLollipopSeries();
  registerMarimekkoSeries();
  registerPieSeries();
  registerRadarSeries();
  registerRadialBarSeries();
  registerRangeSeries();
  registerSankeySeries();
  registerScatterSeries();
  registerSlopeSeries();
  registerSparklineSeries();
  registerSunburstSeries();
  registerTimelineSeries();
  registerTreegraphSeries();
  registerWaterfallSeries();
}
